/*
Eliona API

API to access Eliona Smart Building Assistant

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// Translation Readable text to display in frontend
type Translation struct {
	// German text
	De *string `json:"de,omitempty"`
	// English text
	En *string `json:"en,omitempty"`
}

// NewTranslation instantiates a new Translation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslation() *Translation {
	this := Translation{}
	return &this
}

// NewTranslationWithDefaults instantiates a new Translation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslationWithDefaults() *Translation {
	this := Translation{}
	return &this
}

// GetDe returns the De field value if set, zero value otherwise.
func (o *Translation) GetDe() string {
	if o == nil || o.De == nil {
		var ret string
		return ret
	}
	return *o.De
}

// GetDeOk returns a tuple with the De field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Translation) GetDeOk() (*string, bool) {
	if o == nil || o.De == nil {
		return nil, false
	}
	return o.De, true
}

// HasDe returns a boolean if a field has been set.
func (o *Translation) HasDe() bool {
	if o != nil && o.De != nil {
		return true
	}

	return false
}

// SetDe gets a reference to the given string and assigns it to the De field.
func (o *Translation) SetDe(v string) {
	o.De = &v
}

// GetEn returns the En field value if set, zero value otherwise.
func (o *Translation) GetEn() string {
	if o == nil || o.En == nil {
		var ret string
		return ret
	}
	return *o.En
}

// GetEnOk returns a tuple with the En field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Translation) GetEnOk() (*string, bool) {
	if o == nil || o.En == nil {
		return nil, false
	}
	return o.En, true
}

// HasEn returns a boolean if a field has been set.
func (o *Translation) HasEn() bool {
	if o != nil && o.En != nil {
		return true
	}

	return false
}

// SetEn gets a reference to the given string and assigns it to the En field.
func (o *Translation) SetEn(v string) {
	o.En = &v
}

func (o Translation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.De != nil {
		toSerialize["de"] = o.De
	}
	if o.En != nil {
		toSerialize["en"] = o.En
	}
	return json.Marshal(toSerialize)
}

type NullableTranslation struct {
	value *Translation
	isSet bool
}

func (v NullableTranslation) Get() *Translation {
	return v.value
}

func (v *NullableTranslation) Set(val *Translation) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslation) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslation(val *Translation) *NullableTranslation {
	return &NullableTranslation{value: val, isSet: true}
}

func (v NullableTranslation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
